<!DOCTYPE html>
<%@ page contentType="text/html;charset=utf-8"%>
						<p><strong>cron 표현식</strong></p>
						<p>문자열의 좌측부터 우측까지 아래의 순서대로 의미가 있고 각 항목은 space 문자로 구분한다.</p><!-- Not Allowed Attribute Filtered ( se2_tbl_template="4") -->

						<table style="BORDER-BOTTOM: rgb(199,199,199) 1px solid; BORDER-LEFT: rgb(199,199,199) 1px solid; BORDER-TOP: rgb(199,199,199) 1px solid; BORDER-RIGHT: rgb(199,199,199) 1px solid" class="__se_tbl" border="0" cellspacing="0" cellpadding="0"><tbody><tr><td style="TEXT-ALIGN: left; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(243,243,243); PADDING-LEFT: 4px; WIDTH: 73px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); FONT-WEIGHT: normal; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;순서</p></td><td style="TEXT-ALIGN: left; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(243,243,243); PADDING-LEFT: 4px; WIDTH: 142px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); FONT-WEIGHT: normal; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>필드명</p></td><td style="TEXT-ALIGN: left; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(243,243,243); PADDING-LEFT: 4px; WIDTH: 523px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); FONT-WEIGHT: normal; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>사용 가능한 값</p></td></tr><tr><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 73px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;1</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 142px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;seconds</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 523px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0~59 , - * /</p></td></tr><tr><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 73px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;2</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 142px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;minutes</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 523px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0~59 , - * /</p></td></tr><tr><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 73px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;3</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 142px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;hours</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 523px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0~23 , - * /</p></td></tr><tr><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 73px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;4</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 142px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;day of month</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 523px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;1~31 , - * ? / L W</p></td></tr><tr><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 73px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;5</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 142px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;month</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 523px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;1~12 or JAN-DEC , - * /</p></td></tr><tr><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 73px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;6</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 142px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;day of week</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 523px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;1-7 or SUN-SAT , - * ? / L #</p></td></tr><tr><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 73px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;7</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 142px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;years (optional)</p></td><td style="PADDING-BOTTOM: 2px; BACKGROUND-COLOR: rgb(255,255,255); PADDING-LEFT: 4px; WIDTH: 523px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: rgb(102,102,102); BORDER-TOP: rgb(231,231,231) 1px solid; BORDER-RIGHT: rgb(231,231,231) 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;1970~2099 , - * /</p></td></tr></tbody></table>
						<p>&nbsp;</p>
						<p><strong>특수문자의 의미</strong></p><!-- Not Allowed Attribute Filtered ( se2_tbl_template="4") -->


						<table style="BORDER-BOTTOM: #c7c7c7 1px solid; BORDER-LEFT: #c7c7c7 1px solid; BORDER-TOP: #c7c7c7 1px solid; BORDER-RIGHT: #c7c7c7 1px solid" class="__se_tbl" border="0" cellspacing="0" cellpadding="0"><tbody><tr><td style="BORDER-BOTTOM: medium none; TEXT-ALIGN: left; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #f3f3f3; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: medium none; FONT-WEIGHT: normal; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;기호</p></td><td style="BORDER-BOTTOM: medium none; TEXT-ALIGN: left; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #f3f3f3; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: medium none; FONT-WEIGHT: normal; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>의미&nbsp;</p></td><td style="BORDER-BOTTOM: medium none; TEXT-ALIGN: left; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #f3f3f3; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: medium none; FONT-WEIGHT: normal; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;사용 예</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;*</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;모든 수를 의미</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>seconds에서 사용하면 매초, minutes에서 사용하면 매분, hours에서 사용하면 매시간&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;?</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;해당 항목을 사용하지 않음</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>day of month에서 사용하면 월중 날짜를 지정하지 않음. day of week에서 사용하면 주중 요일을 지정하지 않음&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;-</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;기간을 설정</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>hours에서 10-12이면 10시, 11시, 12시에 동작</p>
						<p>minutes에서 58-59이면 58분, 59분에 동작</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;,</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>특정 시간을 지정</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>day of week에서 2,4,6이면 월,수,금에만 동작함</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;/</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>시작시간과 반복 간격 설정</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 36px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>seconds위치에 0/15로 설정하면 0초에 시작해서 15초 간격으로 동작&nbsp;</p>
						<p>minutes위치에 5/10으로 설정하면 5분에 시작해서 10분 간격으로 동작</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;L</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>마지막 기간에 동작</p>
						<p>day of month, day of week에서만 사용</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>day of month에서 사용하면 해당월 마지막 날에 수행</p>
						<p>day of week에서 사용하면 토요일에 수행</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;W</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>가장 가까운&nbsp;평일 동작</p>
						<p>day of month에만 사용&nbsp;</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>15W로 설정하면 15일이 토요일이면 가장 가까운 14일 금요일에 실행</p>
						<p>15W로 설정하고 15일이 일요일이면 16일에 실행</p>
						<p>15W로 설정하고 15일이 평일이면 15일에 실행</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;LW</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>L과 W의 조합&nbsp;</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>그달의 마지막 평일에 동작&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 81px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;#</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 180px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>몇 번째 주와 요일 설정</p>
						<p>day of week에 사용&nbsp;</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 477px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>6#3이면 3 번째 주 금요일에 동작&nbsp;</p>
						<p>4#2이면 2번째 주 수요일에 동작</p></td></tr></tbody></table>
						<p>&nbsp;</p>
						<p><strong>사용 예</strong></p><!-- Not Allowed Attribute Filtered ( se2_tbl_template="4") -->


						<table style="BORDER-BOTTOM: #c7c7c7 1px solid; BORDER-LEFT: #c7c7c7 1px solid; BORDER-TOP: #c7c7c7 1px solid; BORDER-RIGHT: #c7c7c7 1px solid" class="__se_tbl" border="0" cellspacing="0" cellpadding="0"><tbody><tr><td style="BORDER-BOTTOM: medium none; TEXT-ALIGN: left; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #f3f3f3; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: medium none; FONT-WEIGHT: normal; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;표현식</p></td><td style="BORDER-BOTTOM: medium none; TEXT-ALIGN: left; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #f3f3f3; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: medium none; FONT-WEIGHT: normal; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>의미&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 0 12 * * *</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>매일 12시에 실행&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 15 10 * * *</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>매일 10시 15분에 실행&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 * 14 * * *</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>매일 14시에 0분~59분까지 매분 실행</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 0/5 14 * * *</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>매일 14시에 시작해서 5분 간격으로 실행&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 0/5 14,18 * * *</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>매일 14시, 18시에 시작해서 5분 간격으로 실행&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 0-5 14 * * *</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>매일 14시에&nbsp;0분, 1분, 2분, 3분, 4분, 5분에 실행&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 0 20 ? * MON-FRI</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>월~금일 20시 0분 0초에 실행&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 0/5 14 * * ?</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>아무요일, 매월, 매일 14:00부터 14:05분까지 매분 0초 실행&nbsp;(6번 실행됨)</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 15 10 ? * 6L</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;매월 마지막 금요일 아무날이나 10:15:00에 실행</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;0 15 10&nbsp;15 * ?</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>아무요일, 매월 15일 10:15:00에 실행&nbsp;</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; PADDING-RIGHT: 4px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;* /1 * * * *</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; PADDING-RIGHT: 4px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>매 1분마다 실행</p></td></tr><tr><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 212px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>&nbsp;* /10 * * * *</p></td><td style="BORDER-BOTTOM: medium none; BORDER-LEFT: medium none; PADDING-BOTTOM: 2px; BACKGROUND-COLOR: #ffffff; PADDING-LEFT: 4px; WIDTH: 526px; PADDING-RIGHT: 4px; HEIGHT: 18px; COLOR: #666666; BORDER-TOP: #e7e7e7 1px solid; BORDER-RIGHT: #e7e7e7 1px solid; PADDING-TOP: 3px">
						<p>매 10분마다 실행&nbsp;</p></td></tr></tbody></table>
	
